@startuml AddPaperToProject
!theme plain
hide footbox
actor "User:Collaborator" as u
boundary "AddPaperButton:" as apb
boundary "AddPaperForm:" as apf
control "PaperController:" as apc
boundary "ChoosePaperButton:" as cpb
control "ProjectController:" as pc
database "Database:" as pd

activate u

u -> apb : press()
activate apb

apb ->> apf : show()
deactivate apb

u -> apf : fillSearch()
activate apf

create apc
apf -->> apc : <<create>>
apf ->> apc : getPapersByName()
activate apc


apc ->> pd : getPapersByName()
activate pd

pd -->> apc : papers
deactivate pd

apc -->> apf : papers
destroy apc

create cpb
apf -->> cpb : <<create>>
deactivate apf

u -> cpb : press()
activate cpb

create pc
cpb -->> pc : <<create>>
cpb -> pc : addPaper()
deactivate cpb
activate pc

pc ->> pd : addPaperToProject()
activate pd
deactivate pd

destroy pc
destroy cpb

/'
activate pc

pc -> apb : press()
activate apb

create apc
apb --> apc : <<create>>
deactivate apb
activate apc

create apf
apc --> apf : <<create>>
deactivate apc

pc -> apf : fillContents()
activate apf
deactivate apf

pc -> apf : submitContents()
activate apf

apf -> apc : submit()
destroy apf
activate apc

apc -> pd : findPaper()
activate pd
pd --> apc : paper
deactivate pd

apc -> pd : addPaperToProject()
destroy apc
activate pd
deactivate pd
'/
@enduml