@startuml AddSuggestedPaper
!theme plain
hide footbox
actor Collaborator as pc
boundary PaperView as pv
control PaperController as psc
boundary AddPaperSuggestion as aps
boundary PaperPreview as pp
database Database as pd


activate pc

pc -> pv : open()
activate pv

create psc
pv --> psc : <<create>>
activate psc
deactivate pv

psc -> pd : findRelatedPapers()
activate pd
pd --> psc : papers
deactivate pd

opt papers.Count > 0

	create aps
	psc --> aps : <<create>>
	deactivate psc
	
	note right
	An AddPaperSuggestion
	is created for each
	related paper found
	end note

	loop while ProjectCollaborator wants to add suggested papers

		pc -> aps : press()
		activate aps

		aps -> psc : addSuggestion()
		deactivate aps
		activate psc

		create pp
		psc -> pp : <<create>>
		deactivate psc

		pc -> pp : confirm()
		activate pp

		pp -> psc : confirmAdd()
		destroy pp
		activate psc

		psc -> pd : addPaperToProject()
		activate pd
		deactivate pd

		psc -> aps : <<destroy>>
		deactivate psc
		destroy aps

	end
end

destroy psc
@enduml