@startuml CreateProject
!theme plain
hide footbox
actor "User: Owner" as po
boundary "CreateProjectForm:" as cpb
control "ProjectController:" as cpc
entity "Project:" as p
database "Database:" as pd

activate po

po -> cpb : fillName()
activate cpb
deactivate cpb

po -> cpb : confirm()
activate cpb

create cpc
cpb -->> cpc : <<create>>
deactivate cpb
activate cpc

create p
cpc -->> p : <<create>>

cpc ->> pd : addProject()
destroy cpc
activate pd
deactivate pd
@enduml  
