@startuml DeleteProject
!theme plain
actor ProjectOwner as po
boundary DeleteProjectButton as dpb
control DeleteProjectControl as dpc
boundary DeleteProjectForm as dpf
database ProjectDatabase as pd

activate po

po -> dpb : press()
activate dpb

create dpc
dpb --> dpc : <<create>>
deactivate dpb
activate dpc

create dpf
dpc --> dpf : <<create>>
deactivate dpc

po -> dpf : fillContents()
activate dpf
deactivate dpf

po -> dpf : submit()
activate dpf

dpf -> dpc : submitForm()
destroy dpf
activate dpc

dpc -> pd : deleteProject()
destroy dpc
activate pd
deactivate pd
@enduml