@startuml DeleteProject
!theme plain
hide footbox

actor "User: Owner" as po
boundary "DeleteProjectForm:" as cpb
control "ProjectController:" as cpc
database "Database:" as pd
entity "Project:" as p

activate po

po -> cpb : fillName()
activate cpb
deactivate cpb

po -> cpb : confirm()
activate cpb

create cpc
cpb -->> cpc : <<create>>
deactivate cpb
activate cpc

cpc ->> pd : deleteProject()
destroy cpc
activate pd
pd ->> p : destroy()
destroy p
deactivate pd

/'
actor Owner as po
boundary DeleteProjectButton as dpb
control ProjectController as dpc
boundary DeleteProjectForm as dpf
database Database as pd

activate po

po -> dpb : press()
activate dpb

create dpc
dpb --> dpc : <<create>>
deactivate dpb
activate dpc

create dpf
dpc --> dpf : <<create>>
deactivate dpc

po -> dpf : fillContents()
activate dpf
deactivate dpf

po -> dpf : submit()
activate dpf

dpf -> dpc : submitForm()
destroy dpf
activate dpc

dpc -> pd : deleteProject()
destroy dpc
activate pd
deactivate pd
'/
@enduml