@startuml RemoveCollaborator
!theme plain
hide footbox
actor "User:Owner" as po
boundary "RemoveCollaboratorButton" as rcb
control "ProjectController" as rcc
database "Database" as db

activate po

po -> rcb : press()
activate rcb

create rcc
rcb -->> rcc : <<create>>
rcb ->> rcc : removeCollaborator()
deactivate rcb
activate rcc

rcc ->> db : removeCollaboratorFromProject()
activate db
destroy rcc
deactivate db

destroy rcb
@enduml