@startuml RemovePaperFromProject
!theme plain
hide footbox
actor Owner as po
boundary RemovePaperButton as rpb
control ProjectController as rpc
entity Project as p

activate po

po -> rpb : press()
activate rpb

create rpc
rpb --> rpc : <<create>>
deactivate rpb
activate rpc

rpc -> p : removePaper()
destroy rpc
activate p
deactivate p
@enduml