@startuml RemoveCollaborator
!theme plain
hide footbox
actor Owner as po
boundary RemoveCollaboratorButton as rcb
control ProjectController as rcc
entity Project as p

activate po

po -> rcb : press()
activate rcb

create rcc
rcb --> rcc : <<create>>
deactivate rcb
activate rcc

rcc -> p : removeCollaborator()
destroy rcc
activate p
deactivate p
@enduml