@startuml UseCases
!theme plain
(CreateProject) as crpj
(DeleteProject) as dlpj
(AddCollaborator) as adco
(RemoveCollaborator) as rmco
(AddPaperToProject) as adpa
(AddSuggestedPaper) as adsg
(NoSuggestedPapers) as nosg
(RemovePaperFromProject) as rmpa
:Owner: as po
:Collaborator: as pc

po -r-|> pc

nosg -r-> adsg #line.dashed : <<extend>>

po -l- crpj : <<initiate>>
po -- dlpj : <<initiate>>
po -- adco : <<initiate>>
po -- rmco : <<initiate>>

pc -- adpa : <<initiate>>
pc -u- adsg : <<initiate>>
pc -- rmpa : <<initiate>>
@enduml